# Generated by Django 3.2.8 on 2021-11-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20211106_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='members',
        ),
    ]
